"""empty message

Revision ID: 2d535021ae83
Revises: 
Create Date: 2024-10-18 13:13:53.039524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d535021ae83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productvariationimages')
    op.drop_table('productvariations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_user', 'users', ['user_id'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('productvariations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productvariationimages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('variation_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['productvariations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
