"""empty message

Revision ID: 38e0ad3f0b93
Revises: 47b51a65e335
Create Date: 2024-10-23 20:46:30.843756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e0ad3f0b93'
down_revision = '47b51a65e335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_highlights_product', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_highlight', type_='foreignkey')
        batch_op.drop_column('highlight_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_products_highlight', 'highlights', ['highlight_id'], ['id'])

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_highlights_product', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
