"""empty message

Revision ID: 47b51a65e335
Revises: 314cb97fce52
Create Date: 2024-10-23 20:44:55.100697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b51a65e335'
down_revision = '314cb97fce52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_highlights_product', type_='foreignkey')
        batch_op.drop_column('highlight_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_highlight', 'highlights', ['highlight_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_highlight', type_='foreignkey')
        batch_op.drop_column('highlight_id')

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_highlights_product', 'products', ['highlight_id'], ['id'])

    # ### end Alembic commands ###
