"""empty message

Revision ID: 5ab65cfdfcc4
Revises: e14f20bf9bcf
Create Date: 2024-10-24 14:07:51.182708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab65cfdfcc4'
down_revision = 'e14f20bf9bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productshighlight', type_='foreignkey')
        batch_op.drop_column('highlight_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_productshighlight', 'highlights', ['highlight_id'], ['id'])

    # ### end Alembic commands ###
