"""empty message

Revision ID: 818e065a6e01
Revises: d8356aeb9a11
Create Date: 2024-10-25 08:24:31.783738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818e065a6e01'
down_revision = 'd8356aeb9a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product_highlight')
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    op.create_table('_alembic_tmp_product_highlight',
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('highlight_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'highlight_id')
    )
    # ### end Alembic commands ###
