"""empty message

Revision ID: ca6d890a9c0a
Revises: 
Create Date: 2024-10-23 20:36:50.614369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6d890a9c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brands_product', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_colors_product_variation', type_='foreignkey')
        batch_op.drop_column('variation_id')

    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('_size', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_product_variations_color', 'colors', ['color_id'], ['id'])
        batch_op.drop_column('size')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_brand', 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_brand', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_product_variations_color', type_='foreignkey')
        batch_op.drop_column('_size')
        batch_op.drop_column('color_id')

    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_colors_product_variation', 'product_variations', ['variation_id'], ['id'])

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_brands_product', 'products', ['brand_id'], ['id'])

    # ### end Alembic commands ###
