"""empty message

Revision ID: ce7ac7a488f7
Revises: e56403af2d86
Create Date: 2024-10-24 14:21:28.484556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7ac7a488f7'
down_revision = 'e56403af2d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_highlights_product', type_='foreignkey')
        batch_op.drop_column('highlight')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('highlight', sa.VARCHAR(length=150), nullable=True))
        batch_op.create_foreign_key('fk_highlights_product', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
