"""empty message

Revision ID: d8356aeb9a11
Revises: ce7ac7a488f7
Create Date: 2024-10-24 14:24:07.326167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8356aeb9a11'
down_revision = 'ce7ac7a488f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
