"""empty message

Revision ID: e14f20bf9bcf
Revises: fbc539006daa
Create Date: 2024-10-24 14:02:52.197015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14f20bf9bcf'
down_revision = 'fbc539006daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_highlights_product', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_productshighlight', 'highlights', ['highlight_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productshighlight', type_='foreignkey')
        batch_op.drop_column('highlight_id')

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_highlights_product', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
