"""empty message

Revision ID: e56403af2d86
Revises: 5ab65cfdfcc4
Create Date: 2024-10-24 14:09:07.729029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56403af2d86'
down_revision = '5ab65cfdfcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_highlights_product', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_highlights_product', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
