"""empty message

Revision ID: f67e8a1e11bd
Revises: 9b3963dda99b
Create Date: 2024-10-19 17:24:17.641487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67e8a1e11bd'
down_revision = '9b3963dda99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_items_product', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_cart_items_product', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
